# This Travis-CI file is for testing the state of the MOM6 source code.
# It does NOT test MOM6 functions.

# This is a not a c-language project but it does use "make"
language: c

# Prerequisites for using the Makefile to build MOM6
#install:
# - sudo apt-get install tcsh pkg-config
# - sudo apt-get install gfortran
# - sudo apt-get install netcdf-bin libnetcdf-dev
# - sudo apt-get install openmpi-bin libopenmpi-dev

# Test critical targets in the Makefile
script:
 - pwd ; ls -R
 - echo "Set" ; set
 - echo "Env" ; printenv
