# This Travis-CI file is for testing the state of the MOM6 source code.
# It does NOT test MOM6 functions.

# This is a not a c-language project but it does use "make"
language: c

# Tests to run
script:
 - ./trailer.py trailer.py
 - ./trailer.py -l 120 example.F90 || true
